C Copyright (c) 2014 David Patrick Hodapp
C
C Permission is hereby granted, free of charge, to any person obtaining a copy
C of this software and associated documentation files (the "Software"), to deal
C in the Software without restriction, including without limitation the rights   
C to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
C copies of the Software, and to permit persons to whom the Software is
C furnished to do so, subject to the following conditions:
C
C The above copyright notice and this permission notice shall be included in
C all copies or substantial portions of the Software.
C
C THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
C IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
C FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
C AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
C LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
C OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
C THE SOFTWARE.
C
      REAL(KIND=8) FUNCTION CONV_S_TO_DISP(S,A,W,L,B)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC     
C     PURPOSE:
C     CONVERT VERTICAL BENDING STRESS (S) TO EQUIVALENT  DISPLACEMENT 
C     ASSOCIATED WITH THE UN-CRACKED SPECIMEN (CONTANT 
C     STRAIN/DISPLACEMENT EXPERIMENTS).  
C
C     PARAMETERS:
C     - S: VERTICAL BENDING STRESS [Pa]
C     - A: M(T) SPECIMEN HALF-CRACK LENGTH [m] (SEE ASTM E647-13)
C     - W: M(T) SPECIMEN DIMENSION W [m] (SEE ASTM E647-13)
C     - L: M(T) SPECIMEN DIMENSION L [m] (SEE ASTM E647-13)
C     - B: M(T) SPECIMEN DIMENSION B [m] (SEE ASTM E647-13)
C     OUTPUT:
C     - DISP: EQUIVALENT HALF DISPLACEMENT [m]
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
      IMPLICIT NONE
C
C     DECLARE CALLING PARAMETERS
      REAL(KIND=8), INTENT(IN)  :: S,A,W,L,B
C
C     DECLARE LOCAL VARIABLES
      REAL(KIND=8)            :: PSYOUNGMOD
      REAL(KIND=8), PARAMETER :: YOUNGMOD=2.1E11
      REAL(KIND=8), PARAMETER :: POISSONRATIO=0.3
      PSYOUNGMOD=YOUNGMOD/(1.0-POISSONRATIO**2.0)
C     
C     DETERMINE HELF-DISPLACEMENT OF THE UNCRACKED SPECIMEN
      CONV_S_TO_DISP=0.5*(S/PSYOUNGMOD*2.0*L)
C
      END FUNCTION